.TH "/home/juanse/Documents/GitHub/HC-TTIExp/src/media_properties/EJEMPLO1.cpp" 3 "Mon Jan 22 2024" "Version 1.0" "HCTTIExp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/juanse/Documents/GitHub/HC-TTIExp/src/media_properties/EJEMPLO1.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <vtkSmartPointer\&.h>\fP
.br
\fC#include <vtkDataSetReader\&.h>\fP
.br
\fC#include <vtkDataSetWriter\&.h>\fP
.br
\fC#include <vtkDoubleArray\&.h>\fP
.br
\fC#include <vtkIntArray\&.h>\fP
.br
\fC#include <vtkPoints\&.h>\fP
.br
\fC#include <vtkCellData\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLayerProperties\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 14 of file EJEMPLO1\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HCTTIExp from the source code\&.
