.TH "LithoData" 3 "Mon Jan 22 2024" "Version 1.0" "HCTTIExp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LithoData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcolumn1\fP"
.br
.ti -1c
.RI "double \fBcolumn2\fP"
.br
.ti -1c
.RI "double \fBcolumn3\fP"
.br
.ti -1c
.RI "int \fBcolumn4\fP"
.br
.ti -1c
.RI "double \fBcolumn5\fP"
.br
.ti -1c
.RI "double \fBtemperature_range\fP"
.br
.ti -1c
.RI "double \fBtime_range\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file EJEMPLO2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int LithoData::column1"

.PP
Definition at line 16 of file EJEMPLO2\&.cpp\&.
.SS "double LithoData::column2"

.PP
Definition at line 17 of file EJEMPLO2\&.cpp\&.
.SS "double LithoData::column3"

.PP
Definition at line 18 of file EJEMPLO2\&.cpp\&.
.SS "int LithoData::column4"

.PP
Definition at line 19 of file EJEMPLO2\&.cpp\&.
.SS "double LithoData::column5"

.PP
Definition at line 20 of file EJEMPLO2\&.cpp\&.
.SS "double LithoData::temperature_range"

.PP
Definition at line 21 of file EJEMPLO2\&.cpp\&.
.SS "double LithoData::time_range"

.PP
Definition at line 22 of file EJEMPLO2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HCTTIExp from the source code\&.
