.TH "/home/juanse/Documents/GitHub/HC-TTIExp/src/basic/message.cpp" 3 "Mon Jan 22 2024" "Version 1.0" "HCTTIExp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/juanse/Documents/GitHub/HC-TTIExp/src/basic/message.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <HCTTIExpProjConfig\&.h>\fP
.br
\fC#include <basic/message\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhello_world\fP ()"
.br
.ti -1c
.RI "void \fBprint_version\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void hello_world ()"

.PP
Definition at line 5 of file message\&.cpp\&.
.SS "void print_version ()"

.PP
Definition at line 10 of file message\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HCTTIExp from the source code\&.
