.TH "YourNamespace::LayerProperties" 3 "Mon Jan 22 2024" "Version 1.0" "HCTTIExp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YourNamespace::LayerProperties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< int > \fBlithology_id\fP"
.br
.ti -1c
.RI "std::vector< double > \fBtemperatureRange\fP"
.br
.ti -1c
.RI "std::vector< double > \fBexposureTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file EJEMPLO2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<double> YourNamespace::LayerProperties::exposureTime"

.PP
Definition at line 30 of file EJEMPLO2\&.cpp\&.
.SS "std::vector<int> YourNamespace::LayerProperties::lithology_id"

.PP
Definition at line 28 of file EJEMPLO2\&.cpp\&.
.SS "std::vector<double> YourNamespace::LayerProperties::temperatureRange"

.PP
Definition at line 29 of file EJEMPLO2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HCTTIExp from the source code\&.
