.TH "YourNamespace::YourClass" 3 "Mon Jan 22 2024" "Version 1.0" "HCTTIExp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YourNamespace::YourClass
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::vector< vtkSmartPointer< vtkUnstructuredGrid > > \fBmodifyGrids\fP (const std::string &gridFilename, const std::string &lithoFilename)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddScalarArrayToGrid\fP (vtkSmartPointer< vtkUnstructuredGrid > &grid, double value, const char *arrayName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file EJEMPLO2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void YourNamespace::YourClass::addScalarArrayToGrid (vtkSmartPointer< vtkUnstructuredGrid > & grid, double value, const char * arrayName)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 76 of file EJEMPLO2\&.cpp\&.
.SS "std::vector<vtkSmartPointer<vtkUnstructuredGrid> > YourNamespace::YourClass::modifyGrids (const std::string & gridFilename, const std::string & lithoFilename)\fC [inline]\fP"

.PP
Definition at line 36 of file EJEMPLO2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HCTTIExp from the source code\&.
