.TH "YourNamespace" 3 "Mon Jan 22 2024" "Version 1.0" "HCTTIExp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YourNamespace
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLayerProperties\fP"
.br
.ti -1c
.RI "class \fBYourClass\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HCTTIExp from the source code\&.
